image: haskell:latest

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/

build-job:
  stage: build
  script:
    - stack --system-ghc --stack-root ${STACK_ROOT} build

operators:
  stage: test
  script:
    - stack --system-ghc --stack-root ${STACK_ROOT} test :operators

functions:
  stage: test
  script:
    - stack --system-ghc  --stack-root ${STACK_ROOT} test :functions

collatz:
  stage: test
  script:
    - stack --system-ghc --stack-root ${STACK_ROOT} test :collatz

fact:
  stage: test
  script:
    - stack --system-ghc --stack-root ${STACK_ROOT} test :fact
