image: haskell:8.10.4

stages:
  - build
  - test

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  STACK_OPTS: "--fast --system-ghc"

cache:
  paths:
    - .stack-work/
    - .stack-root/

build-job:
  stage: build
  script:
    - ghc --version
    - stack $STACK_OPTS build

operators:
  stage: test
  script:
    - ghc --version
    - stack $STACK_OPTS test :operators

functions:
  stage: test
  script:
    - stack $STACK_OPTS test :functions

collatz:
  stage: test
  script:
    - stack $STACK_OPTS test :collatz

fact:
  stage: test
  script:
    - stack $STACK_OPTS test :fact
