image: haskell:8.8.4

stages:
  - test

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  STACK_OPTS: "--system-ghc"

operators:
  stage: test
  script:
    - stack $STACK_OPTS test :operators

functions:
  stage: test
  script:
    - stack $STACK_OPTS test :functions

collatz:
  stage: test
  script:
    - stack $STACK_OPTS test :collatz

fact:
  stage: test
  script:
    - stack $STACK_OPTS test :fact

all:
  stage: test
  script:
    - stack $STACK_OPTS test :operators
    - stack $STACK_OPTS test :functions
    - stack $STACK_OPTS test :collatz
    - stack $STACK_OPTS test :fact
