image: haskell:latest

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack


build-job:
  stage: build
  script:
    - stack --stack-root ${STACK_ROOT} build

operators:
  stage: test
  script:
    - stack --stack-root ${STACK_ROOT} test :operators

functions:
  stage: test
  script:
    - stack --stack-root ${STACK_ROOT} test :functions

collatz:
  stage: test
  script:
    - stack --stack-root ${STACK_ROOT} test :collatz

fact:
  stage: test
  script:
    - stack --stack-root ${STACK_ROOT} test :fact
