image: haskell:latest

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  script:
    - stack build

Operators:
  stage: test
  script:
    - stack test :operators

Functions:
  stage: test
  script:
    - stack test :functions

Fact:
  stage: test
  script:
    - stack test :fact
