name:                FunctionsHTemplate
version:             0.1.0.0
github:              "githubuser/FunctionsHTemplate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FunctionsHTemplate#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck


library:
  source-dirs: src

executables:
  FunctionsHTemplate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionsHTemplate

tests:
  operators:
    main:                OperatorsTest
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionsHTemplate

  functions:
    main:                FunctionsTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  collatz:
    main:                CollatzTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  fact:
    main:                FactTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  binom:
    main:                BinomTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  ggt:
    main:                GgtTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  fib:
    main:                FibTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate

  demorgan:
    main:                DeMorganTest
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunctionsHTemplate
