name: GitHub Classroom Workflow
on: [push]
jobs:
  list:
    name: HaskellTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: stack build
      - run: stack test
